name: "Run"
on: [pull_request, push]

jobs:
  defaults:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
    - uses: mymindstorm/setup-emsdk@master

    - name: Verify
      run: emcc -v
  cache-test:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@master
        with:
          version: 1.38.40

      - name: Verify
        run: emcc -v
  no-cache-test:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@master
        with:
          version: 1.38.40
          no-cache: true

      - name: Verify
        run: emcc -v
  no-install:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@master
        with:
          no-install: true

      - name: Verify
        run: emsdk list
